export enum OpenAiPrompts {
  START = 'Користувач розпочав взаємодію з ботом. Напиши привітальне повідомлення, в якому пояснюється, що бот допомагає з оформленням автострахування. Попроси користувача надіслати фото паспорта та техпаспорта.',
  CONFIRM_PRICE_YES = 'Користувач погодився на запропоновану ціну автострахування. Відповідь має бути короткою, ввічливою та підтверджувати прийом замовлення.',
  CONFIRM_PRICE_NO = 'Користувач не погодився з ціною автострахування. Повідом, що ціна фіксована і становить 100 USD. Зроби це ввічливо, але чітко.',
  SEND_PRICE = 'Повідом користувачу, що вартість автострахування є фіксованою і складає 100 USD. Запитай, чи погоджується він з цією ціною.',
  POLICY_GENERATION = 'Користувач погодився на все і оформив автострахування. Створи короткий шаблон поліса автострахування, згенерований штучним інтелектом. Використовуй формальний і офіційний стиль.',
  DOCUMENT_UPLOAD_INSUFFICIENT = 'Користувач завантажив недостатньо фотографій. Попроси надіслати ще одну.',
  DOCUMENT_UPLOAD_TOO_MANY = 'Користувач завантажив забагато фотографій. Попроси видалити зайві та завантажити лише 2 фото.',
  DOCUMENT_UPLOAD_SUCCESS = 'Користувач успішно завантажив усі документи. Підтвердіть успішне завантаження.',
  ERROR = 'Сталася помилка під час обробки вашого запиту. Спробуйте пізніше.',
  INVALID_PASSPORT_DATA = 'Фотографії паспорта не пройшли валідацію. Повідомте користувача.',
  CONFIRMATION = 'Користувач завершив процес завантаження документів. Згенеруйте повідомлення з підтвердженням і деталями страхового поліса.',
  DATA_CONFIRMATION = 'Користувач підтвердив, що дані, зчитані з документів, є правильними. Подякуй за підтвердження та повідом, що зараз буде запропонована ціна.',
  DATA_REJECTED = 'Користувач відхилив дані з документів. Попроси зробити нове фото та надіслати його повторно для зчитування інформації.',
  RETRY_DOCUMENT_UPLOAD = 'Під час обробки документа сталася помилка. Будь ласка, зробіть нове фото і завантажте його ще раз.',
  CONFIRM_EXTRACTED_DATA = 'Ось дані, зчитані з ваших документів: [вставити дані]. Якщо все правильно, підтвердіть. Якщо ні — відхиліть.',
}

export enum OpenAiPromptsStatus {
  START = 'START',
  CONFIRM_PRICE_YES = 'CONFIRM_PRICE_YES',
  CONFIRM_PRICE_NO = 'CONFIRM_PRICE_NO',
  INVALID_PASSPORT_DATA = 'INVALID_PASSPORT_DATA',
  CONFIRMATION = 'CONFIRMATION',
  ERROR = 'Что-то пошло не так, попробуйте еще раз',
  DOCUMENT_UPLOAD_SUCCESS = 'DOCUMENT_UPLOAD_SUCCESS',
  DOCUMENT_UPLOAD_INSUFFICIENT = 'DOCUMENT_UPLOAD_INSUFFICIENT',
  DOCUMENT_UPLOAD_TOO_MANY = 'DOCUMENT_UPLOAD_TOO_MANY',
  SEND_PRICE = 'SEND_PRICE',
  DATA_REJECTED = 'DATA_REJECTED',
  POLICY_GENERATION = 'POLICY_GENERATION',
  DATA_CONFIRMATION = 'DATA_CONFIRMATION',
  RETRY_DOCUMENT_UPLOAD = 'RETRY_DOCUMENT_UPLOAD',
  CONFIRM_EXTRACTED_DATA = 'CONFIRM_EXTRACTED_DATA',
}
